<?php

namespace Database\Seeders;

use App\Models\Page;
use Illuminate\Database\Seeder;

class PagesSeeder extends Seeder
{
    public function run()
    {
        $pages = [
            [
                'id' => 1,
                'title' => 'About us',
                'short_description' => 'Who we are?',
                'description' => '<p><meta charset="utf-8"><span style="white-space:pre-wrap;">Our dental consultants can support with excellence in guidance with dental care and oral health services in this country. We’ve been growing since with over 50 clinics across 15 cities. You can enjoy a wide range of services for fulfilling your needs in cosmetic, preventive, restorative, and advanced dental treatments.</span><meta charset="utf-8"><span style="white-space:pre-wrap;">Our dental consultants can support with excellence in guidance with dental care and oral health services in this country.&nbsp;</span></p>',
                'image_1' => null,
                'image_2' => null,
                'banner_image' => null,
                'order' => 1,
                'status' => 1,
                'slug' => 'about-us',
                'seo_title' => 'About us',
                'seo_schema' => 'About us',
                'meta_keywords' => 'About us',
                'meta_description' => 'About us',
                'created_at' => '2024-09-20 02:16:42',
                'updated_at' => '2024-09-20 02:26:58',
            ],
            [
                'id' => 2,
                'title' => 'Why Choose Us',
                'short_description' => 'Why Choose Us',
                'description' => '<p>Why Choose Us&nbsp;</p>',
                'image_1' => null,
                'image_2' => null,
                'banner_image' => null,
                'order' => 1,
                'status' => 1,
                'slug' => 'why-choose-us',
                'seo_title' => 'Why Choose Us',
                'seo_schema' => 'Why Choose Us',
                'meta_keywords' => 'Why Choose Us',
                'meta_description' => 'Why Choose Us',
                'created_at' => '2024-09-20 02:18:17',
                'updated_at' => '2024-09-20 02:18:17',
            ],
            [
                'id' => 3,
                'title' => 'Our Team',
                'short_description' => 'Our Team',
                'description' => '<p>Our Team</p>',
                'image_1' => null,
                'image_2' => null,
                'banner_image' => null,
                'order' => 1,
                'status' => 1,
                'slug' => 'our-team',
                'seo_title' => 'Our Team',
                'seo_schema' => 'Our Team',
                'meta_keywords' => 'Our Team',
                'meta_description' => 'Our Team',
                'created_at' => '2024-09-20 02:18:44',
                'updated_at' => '2024-09-20 02:18:44',
            ],
            [
                'id' => 4,
                'title' => 'Faq',
                'short_description' => 'Faq',
                'description' => '<p>Faq</p>',
                'image_1' => null,
                'image_2' => null,
                'banner_image' => null,
                'order' => 1,
                'status' => 1,
                'slug' => 'faq',
                'seo_title' => 'Faq',
                'seo_schema' => 'Faq',
                'meta_keywords' => 'Faq',
                'meta_description' => 'Faq',
                'created_at' => '2024-09-20 02:19:17',
                'updated_at' => '2024-09-20 02:19:17',
            ],
            [
                'id' => 5,
                'title' => 'Destination',
                'short_description' => 'Destination',
                'description' => '<p>Destination</p>',
                'image_1' => null,
                'image_2' => null,
                'banner_image' => null,
                'order' => 1,
                'status' => 1,
                'slug' => 'destination',
                'seo_title' => 'Destination',
                'seo_schema' => 'Destination',
                'meta_keywords' => 'Destination',
                'meta_description' => 'Destination',
                'created_at' => '2024-09-20 02:20:25',
                'updated_at' => '2024-09-20 02:20:34',
            ],
            [
                'id' => 6,
                'title' => 'Blog',
                'short_description' => 'Blog',
                'description' => '<p>Blog</p>',
                'image_1' => null,
                'image_2' => null,
                'banner_image' => null,
                'order' => 1,
                'status' => 1,
                'slug' => 'blog',
                'seo_title' => 'Blog',
                'seo_schema' => 'Blog',
                'meta_keywords' => 'Blog',
                'meta_description' => 'Blog',
                'created_at' => '2024-09-20 02:20:56',
                'updated_at' => '2024-09-20 02:21:04',
            ],
            [
                'id' => 7,
                'title' => 'Course',
                'short_description' => 'Course',
                'description' => '<p>Course</p>',
                'image_1' => null,
                'image_2' => null,
                'banner_image' => null,
                'order' => 1,
                'status' => 1,
                'slug' => 'course',
                'seo_title' => 'Course',
                'seo_schema' => 'Course',
                'meta_keywords' => 'Course',
                'meta_description' => 'Course',
                'created_at' => '2024-09-20 02:21:24',
                'updated_at' => '2024-09-20 02:21:32',
            ],
            [
                'id' => 8,
                'title' => 'Service',
                'short_description' => 'Service',
                'description' => '<p>Service</p>',
                'image_1' => null,
                'image_2' => null,
                'banner_image' => null,
                'order' => 1,
                'status' => 1,
                'slug' => 'service',
                'seo_title' => 'Service',
                'seo_schema' => 'Service',
                'meta_keywords' => 'Service',
                'meta_description' => 'Service',
                'created_at' => '2024-09-20 02:22:02',
                'updated_at' => '2024-09-20 02:22:02',
            ],
            [
                'id' => 9,
                'title' => 'Contact Us',
                'short_description' => 'Contact Us',
                'description' => '<p>Contact Us</p>',
                'image_1' => null,
                'image_2' => null,
                'banner_image' => null,
                'order' => 1,
                'status' => 1,
                'slug' => 'contact-us',
                'seo_title' => 'Contact Us',
                'seo_schema' => 'Contact Us',
                'meta_keywords' => 'Contact Us',
                'meta_description' => 'Contact Us',
                'created_at' => '2024-09-20 02:22:41',
                'updated_at' => '2024-09-20 02:23:15',
            ],
            [
                'id' => 10,
                'title' => 'Register',
                'short_description' => 'Register',
                'description' => '<p>Register</p>',
                'image_1' => null,
                'image_2' => null,
                'banner_image' => null,
                'order' => 1,
                'status' => 1,
                'slug' => 'register',
                'seo_title' => 'Register',
                'seo_schema' => 'Register',
                'meta_keywords' => 'Register',
                'meta_description' => 'Register',
                'created_at' => '2024-09-20 02:23:08',
                'updated_at' => '2024-09-20 02:23:08',
            ],
            [
                'id' => 11,
                'title' => 'Our Vision',
                'short_description' => 'Our education consultants can support with excellence in guidance with education and visa consultancy in this country. We’ve been growing since with over 50 branches across 15 countries. You can enjoy a wide range of services for fulfilling your dreams to study in Australia, the UK, Canada and the US.',
                'description' => '<p><meta charset="utf-8"><span style="white-space:pre-wrap;">Our dental consultants can support with excellence in guidance with dental care and oral health services in this country. We’ve been growing since with over 50 clinics across 15 cities. You can enjoy a wide range of services for fulfilling your needs in cosmetic, preventive, restorative, and advanced dental treatments.</span><meta charset="utf-8"><span style="white-space:pre-wrap;">Our dental consultants can support with excellence in guidance with dental care and oral health services in this country.&nbsp;</span></p>',
                'image_1' => null,
                'image_2' => null,
                'banner_image' => null,
                'order' => 1,
                'status' => 1,
                'slug' => 'our-vision',
                'seo_title' => 'Our Vision',
                'seo_schema' => null,
                'meta_keywords' => null,
                'meta_description' => null,
                'created_at' => '2024-09-20 02:28:56',
                'updated_at' => '2024-09-20 02:28:56',
            ],
            [
                'id' => 12,
                'title' => 'Our Mission',
                'short_description' => 'Our dental professionals can support with excellence in guidance with oral health care and advanced dental services in this country. We’ve been growing steadily with over 50 clinics across 15 cities. You can enjoy a wide range of services for fulfilling your needs in preventive, cosmetic, restorative, and advanced dental treatments.',
                'description' => '<p><meta charset="utf-8"><span style="white-space:pre-wrap;">Our dental consultants can support with excellence in guidance with dental care and oral health services in this country. We’ve been growing since with over 50 clinics across 15 cities. You can enjoy a wide range of services for fulfilling your needs in cosmetic, preventive, restorative, and advanced dental treatments.</span><meta charset="utf-8"><span style="white-space:pre-wrap;">Our dental consultants can support with excellence in guidance with dental care and oral health services in this country.&nbsp;</span></p>',
                'image_1' => null,
                'image_2' => null,
                'banner_image' => null,
                'order' => 1,
                'status' => 1,
                'slug' => 'our-mission',
                'seo_title' => 'Our Mission',
                'seo_schema' => 'Our Mission',
                'meta_keywords' => 'Our Mission',
                'meta_description' => 'Our Mission',
                'created_at' => '2024-09-20 02:29:37',
                'updated_at' => '2024-09-20 02:29:37',
            ],
            [
                'id' => 13,
                'title' => 'Message from CEO',
                'short_description' => 'ceoname',
                'description' => '<p><meta charset="utf-8"><span style="white-space:pre-wrap;">I am delighted to extend a warm welcome to you on behalf of Om\'s Dental Care, your trusted partner in oral health and advanced dental treatment. We take immense pride in our skilled and compassionate team, dedicated to providing efficient, comfortable, and personalized dental services for every patient. As the Director of Om\'s Dental Care, I invite you to explore the wide range of modern dental solutions and treatment options we offer. It is our mission to contribute to healthier smiles and improved oral well-being for people in Pokhara. Just as we established Om\'s Dental Care with a vision of excellence, we now encourage you to take the next step toward a confident smile by exploring the comprehensive dental services available at our clinic. Oral health is the foundation of overall well-being, and we are here to help you achieve and maintain it with us.</span><br><span style="white-space:pre-wrap;">I am delighted to extend a warm welcome to you on behalf of Om\'s Dental Care, your trusted partner in oral health and advanced dental treatment. We take immense pride in our skilled and compassionate team, dedicated to providing efficient, comfortable, and personalized dental services for every patient. As the Director of Om\'s Dental Care, I invite you to explore the wide range of modern dental solutions and treatment options we offer. It is our mission to contribute to healthier smiles and improved oral well-being for people in Pokhara. Just as we established Om\'s Dental Care, we now encourage you to take the next step toward better oral health by exploring the various dental care services available through us.</span></p>',
                'image_1' => null,
                'image_2' => null,
                'banner_image' => null,
                'order' => 1,
                'status' => 1,
                'slug' => 'message-from-ceo',
                'seo_title' => 'Message from CEO',
                'seo_schema' => 'Message from CEO',
                'meta_keywords' => 'Message from CEO',
                'meta_description' => 'Message from CEO',
                'created_at' => '2024-09-20 02:30:22',
                'updated_at' => '2024-09-20 02:42:44',
            ],
            [
                'id' => 14,
                'title' => 'Testimonial',
                'short_description' => 'Testimonial',
                'description' => '<p>Testimonial</p>',
                'image_1' => null,
                'image_2' => null,
                'banner_image' => null,
                'order' => 1,
                'status' => 1,
                'slug' => 'testimonial',
                'seo_title' => 'Testimonial',
                'seo_schema' => 'Testimonial',
                'meta_keywords' => 'Testimonial',
                'meta_description' => 'Testimonial',
                'created_at' => '2024-09-20 02:50:37',
                'updated_at' => '2024-09-20 02:50:37',
            ],
            [
                'id' => 15,
                'title' => 'University',
                'short_description' => 'University',
                'description' => 'University',
                'image_1' => null,
                'image_2' => null,
                'banner_image' => null,
                'order' => 1,
                'status' => 1,
                'slug' => 'university',
                'seo_title' => 'University',
                'seo_schema' => 'University',
                'meta_keywords' => 'University',
                'meta_description' => 'University',
                'created_at' => '2024-09-20 02:50:37',
                'updated_at' => '2024-09-20 02:50:37',
            ],
        ];

        if (count($pages)) {
            foreach ($pages as $page) {
                Page::create($page);
            }
        }
    }
}
